In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
df = pd.read_csv("/content/author_ru_utf.csv", encoding='UTF8')

In [ ]:
x = df.iloc[:, 2:-1]
y = df['Author']
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
bays = MultinomialNB().fit(X_train, y_train)

In [ ]:
predictions = bays.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

0.8586956521739131
[[10  0  0  1]
 [ 0 17  0  0]
 [ 3  1 32  1]
 [ 3  1  3 20]]
